title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://yeonpark.github.io
# Remote Setting
baseurl: "/guidelines"
# url: ""

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
